[project]
name = "llm-scratch"
version = "0.1.0"
description = "밑바닥부터 만들면서 배우는 LLM 실습 코드"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "torch>=2.10.0",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
